-- ============================================================
-- SEED DATA: Hadiran RT — migrasi dari Google Apps Script
-- Jalankan berurutan: Section 1 → 2 → 3 → 4 → 5
-- ============================================================

-- ============================================================
-- SECTION 1: WARGA (70 anggota, 69 aktif + 1 nonaktif)
-- ============================================================
INSERT INTO warga (nama, status_aktif) VALUES
('Ach.Bayu Octamar',        true),
('Ahmad Iqbal',             true),
('Ahmad Fauzi',             true),
('Amirudin Basori',         true),
('Arpandi',                 true),
('Arga Julian',             true),
('Basukianto',              true),
('Bayu Wiyasanyata',        true),
('Bedianto',                true),
('Boin',                    true),
('Carduki',                 true),
('Dedi Iskandar',           true),
('Devit',                   true),
('Dhiman',                  true),
('Farida',                  true),
('Hafid Dasuni',            true),
('H.Deny Fredianto',        true),
('H.Kadimun',               true),
('H.Mustain Tabrani',       true),
('H.Naba Hendrawan',        true),
('H.Rohsaidin',             true),
('H.Yatmo Saleh',           true),
('Idham Firmansyah',        true),
('Imam Slamet',             true),
('Indra Irawan',            true),
('Irwansyah',               true),
('Jamiat',                  true),
('Karta Saleh',             true),
('Komarudin',               true),
('Kunto Mulyono',           true),
('Lisun ( Cokri )',         true),
('Melky',                   true),
('Minan Kinan',             true),
('Musa',                    false),
('Muchlis',                 true),
('M.Aryanto',               true),
('M.Suryadi',               true),
('Nasuha',                  true),
('Nazarudin',               true),
('Nikin Sapari ( Boy )',     true),
('Niman Borti',             true),
('Nisan Nasrullah ( Icang )', true),
('Nurdjaman',               true),
('Nurdin Abet',             true),
('Farid Hamdzah',           true),
('Rahmat Deni',             true),
('Rahma',                   true),
('Riduan Tagor',            true),
('Riky Kurniawan',          true),
('Robyansyah',              true),
('Romaidi Hasan',           true),
('Saan Kinan',              true),
('Saan Simin',              true),
('Sahroni / Eti',           true),
('Sahlani',                 true),
('Sain Simin',              true),
('Sain Suhendi',            true),
('Saman Ma''arif',          true),
('Saman Suryadi ( Mono )',  true),
('Suhardi Nur',             true),
('Surmansyah',              true),
('Syarifudin',              true),
('Tasim Payakun',           true),
('Tasman H.Sainan',         true),
('Tuhu Wiyono',             true),
('Ustad Saiful Hadi',       true),
('Wahyudi',                 true),
('Wawan R Irawan',          true),
('Yulianto',                true),
('Zulkarnain Bontot',       true);
